#!/bin/bash
set -e

# stop service before removal
systemctl stop wgupdown.service || true
systemctl stop wgupdown-gui.service || true

systemctl disable wgupdown.service || true
systemctl disable wgupdown-gui.service || true

systemctl daemon-reload

exit 0