package config

import (
	"fmt"
	"path"

	"os"
	"path/filepath"

	"github.com/ilyakaznacheev/cleanenv"
)

type (
	Config struct {
		Cli `yaml:"cli"`
	}

	Cli struct {
		Interface string `env-required:"true" yaml:"interface"`
	}
)

func NewConfig(configPath string) (*Config, error) {
	cfg := &Config{}

	err := cleanenv.ReadConfig(path.Join("./", configPath), cfg)
	if err != nil {
		return nil, fmt.Errorf("error reading config file: %w", err)
	}

	err = cleanenv.ReadEnv(cfg)
	if err != nil {
		return nil, fmt.Errorf("error loading env: %w", err)
	}

	return cfg, nil
}

func CreateEnvFile(envDir string, config *Config) error {
	if err := os.MkdirAll(envDir, 0o755); err != nil {
		return fmt.Errorf("failed to create env directory: %w", err)
	}

	envPath := filepath.Join(envDir, "wgupdown.generated.env")
	file, err := os.OpenFile(envPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		return fmt.Errorf("failed to create env file: %w", err)
	}
	defer file.Close()

	content := fmt.Sprintf(`# AUTO-GENERATED FILE — DO NOT EDIT
# Generated by wgupdown-gui
WG_INTERFACE=%s
`, config.Cli.Interface)

	if _, err := file.WriteString(content); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}

	return nil
}
